
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const TransactionType = {
  INCOME: 'INCOME',
  OUTCOME: 'OUTCOME'
} as const

export type TransactionType = (typeof TransactionType)[keyof typeof TransactionType]
